### ISSUE TITLE
add empty string support

### ISSUE THREAD

**Issue by petrolifero** [rain-1/racket-peg#46]
```
#lang peg

a <- '' 'a' ;
```

this don't work.  Because expect to have at least one char inside single quotes

**Comment by rain-1** [comment]
This is a really interesting bug! Thanks for finding it.

I tested in drracket by applying the peg in peg parser to `foo <- 'a';` and `foo <- '';`

i saw the AST comes out as `(primary literal "a")` and `(primary literal)`... because of the way empty string = null sequence in PEG result.

I'm not 100% sure how to address this. I fixed it this way. but it seems like it will be a problem for anybody making a parser with this, so we need to think about it more https://github.com/rain-1/racket-peg/commit/97c76c4aec21c7d009c4c560aa6bc5c9b540e905

**Comment by petrolifero** [comment]
A person doing a parser with this will use semantic actions so (s)he don't will get in trouble

**Comment by petrolifero** [comment]
Can you provide some example of trouble that can be made because of implementation in this way? If not, i want to close this issue that looks like closed to me

**Comment by rain-1** [comment]
Well basically anybody who implements a parser (like we implemented the PEG parser), will have to add a special rule to handle empty strings (like we did `(primary literal)`).

I think this will be a pitfall that happens for people using the library.

**Comment by petrolifero** [comment]
```
#lang peg

(require "s-exp.rkt");

...

literal <-- ~['] v:(~[\\] ['\\] / !['\\] .)* ~['] _ -> (if v (list 'literal v) (list 'literal ""));

...
peg <-- _ import* rule+;
import <-- s-exp _ ';' _;
```

in this way, the semantic action can be used preserving the structure that would be generated.

**Comment by rain-1** [comment]
yes it's true but the root problem remains

**Comment by petrolifero** [comment]
The parser, when he see that * don't match one char, return a empty list. If he can infer the type of the nonterminal, he can return directly a empty string and the user will not need to handle special case

**Comment by petrolifero** [comment]
If the user must put the type of a non-terminal? If there's no type, the parser infer string.

Will look beaitufil yet


`a:int <- v:[0-9]+ -> (string->symbol v) ;`

and we can export some constants like a.type to parser can generate empty string if necessary

**Comment by rain-1** [comment]
The relevant source file is https://github.com/rain-1/racket-peg/blob/master/peg-result.rkt

We can't add a type system because we want this to work naturally inside scheme.

**Comment by petrolifero** [comment]
The problem is when is a string or not. Maybe the method can receive a "string?" To see if generate ("") or ()
